name: Tests
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    FORCE_COLOR: "1" # Make tools pretty.
    PIP_DISABLE_PIP_VERSION_CHECK: "1"
    PIP_NO_PYTHON_VERSION_WARNING: "1"

jobs:
    python:
        name: ${{ matrix.tox || matrix.python }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - { python: "3.14" }
                    - { python: "3.13" }
                    - { python: "3.12" }
                    - { python: "3.11" }
                    - { python: "3.11", tox: "style" }
        steps:
            - uses: actions/checkout@v4
            - uses: astral-sh/setup-uv@6
              with:
                  enable-cache: true
                  prune-cache: false
            - uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python }}
            - run: uv run --group tox --locked tox run -e ${{ matrix.tox || format('py{0}', matrix.python) }}
    typing:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: astral-sh/setup-uv@6
              with:
                  enable-cache: true
                  prune-cache: false
            - uses: actions/setup-python@v5
              with:
                  python-version-file: "pyproject.toml"
            - name: cache mypy
              uses: actions/cache@4
              with:
                  path: ./.mypy_cache
                  key: mypy|${{ hashFiles('pyproject.toml') }}
            - run: uv run --group tox --locked tox run -e typing
